version:  '3'
services:
  band-data-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /var/app/node_modules
      - .:/var/app/
    restart: "no"